#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2020--, The Qiita Development Team.
#
# Distributed under the terms of the BSD 3-clause License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

import sys
from qp_woltka.util import demux

input_ = sys.stdin.buffer
output = sys.argv[1].encode('ascii')
demux(input_, output)
